### ISSUE TITLE
Build requires missing 'makeheader' and won't work if provided

### ISSUE THREAD

**Issue by Bengrs** [Olde-Skuul/burgerlib#10]
Hello,

I'm trying to build burgerlib for MacOS 12 arm64.

It requires a 'makeheader' tool that can't be found anywhere but in a prebuilt form in the KitchenSink repo which haven't been updated in years. **What is the proper way to get this tool?**

After installing the makeheader in PATH, allowing the tool full access to the drive and cleaning quarantine xattr flag, the build won't proceed:
```
makeheader /Users/someuser/Documents/burgerlib-master/source/templateburgerbase.h /Users/someuser/Documents/burgerlib-master/bin/burger.h
Can't open Users:someuser:Documents:burgerlib-master:source:templateburgerbase.h:
```

`/Users/someuser/Documents/burgerlib-master/source/templateburgerbase.h` does exists and is accessible.

**Comment by burgerbecky** [comment]
I'll include a binary shortly. I have a version that runs fine on an m1 mac

**Comment by burgerbecky** [comment]
This issue is fixed. Closing now
